### PR TITLE
Chain off click and release methods

### LINKED ISSUE #1334: Link click incompatibility with Shoes 3
Reported via https://github.com/shoes/shoesrb.com/pull/78

Running this app works fine under Shoes 3:

```
Shoes.app do
  para "what ", link("does ").click { alert "yo" }, "this do"
  para "how", link("about ") { alert "YO" }, "this?"
end
```

Running the same under Shoes 4 shows something weird (`to_s` on a `Proc` where the link should be), then crashes

image

```
NoMethodError: private method `warn' called for #<Shoes::InternalApp:0xa20b94b>
                         text_block_guard at /Users/jason/source/shoes4/shoes-core/lib/shoes/link.rb:70
                                 visible? at /Users/jason/source/shoes4/shoes-core/lib/shoes/link.rb:57
                         element_visible? at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:55
                                mouse_on? at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:50
  block in cursor_over_clickable_element? at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:63
                                     any? at org/jruby/RubyArray.java:4299
           cursor_over_clickable_element? at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:62
                      mouse_shape_control at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:25
                                mouseMove at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/mouse_move_listener.rb:13
                           run_event_loop at /Users/jason/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/swt-4.4/lib/swt/minimal.rb:109
                               event_loop at /Users/jason/.rbenv/versions/jruby-9.1.6.0/lib/ruby/gems/shared/gems/swt-4.4/lib/swt/minimal.rb:92
                                     open at /Users/jason/source/shoes4/shoes-swt/lib/shoes/swt/app.rb:49
                                 open_gui at /Users/jason/source/shoes4/shoes-core/lib/shoes/internal_app.rb:120
                               initialize at /Users/jason/source/shoes4/shoes-core/lib/shoes/app.rb:50
                                      app at /Users/jason/source/shoes4/shoes-core/lib/shoes/app.rb:19
                                   <main> at /Users/jason/source/shoes4/testing/link_click.rb:1
                                     load at org/jruby/RubyKernel.java:977
                                   (root) at /Users/jason/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:1
                              execute_app at /Users/jason/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:58
                                   <main> at /Users/jason/source/shoes4/shoes-core/lib/shoes/ui/cli.rb:72
                                     load at org/jruby/RubyKernel.java:977
                                   <main> at /Users/jason/source/shoes4/shoes-swt/bin/shoes-swt:11
```

### PR DESCRIPTION
**Pull request by jasonrclark**
Another fine tutorial find from @snood1205. This PR fixes #1334.

Turns out that back in Shoes 3, the `click` and `release` methods returned their target element so you could chain them. Sensible enough, but we weren't doing it.

Updated the common module for clicking to handle this and slapped the shared example for it on more elements that actually have it.

Two special cases emerged. First was `link`, which despite being the actual source of the bug in the first place doesn't use `Common::Clickable` (for fairly plausible reasons) and didn't get picked up.

Second odd turn was noticing that `Shoes::Button` used `Common::Clickable` but didn't actually support `release`. Turns out Shoes 3 didn't either on buttons (which makes good enough since... with buttons there's really just clicking them, right?) so I removed it at the DSL level so prevent you from calling things that aren't allowed.

### CODE REVIEW

File: shoes-core/lib/shoes/common/clickable.rb [hunk 1]
```diff
@@ -5,10 +5,12 @@ module Clickable
 
       def click(&blk)
         @gui.click blk
+        self
       end
 
       def release(&blk)
         @gui.release blk
+        self
```
Comment (PragTob) [inline shoes-core/lib/shoes/common/clickable.rb]: I love returning self to allow chainability, we might even want to do it in more/other places :) But, some other time you know!

File: shoes-core/spec/shoes/button_spec.rb [hunk 2]
```diff
@@ -52,4 +52,10 @@
     subject { Shoes::Button.new(app, parent, "text", negative_opts, input_block) }
     it_behaves_like "object with negative dimensions"
   end
+
+  describe "no release" do
+    it "doesn't allow releasing despite allowing clicks" do
+      expect { subject.release {} }.to raise_error(NoMethodError)
```
Comment (PragTob) [inline shoes-core/spec/shoes/button_spec.rb]: hm wouldn't `expect(subject).not_to respond_to(:release)` (might have to be be_respond_to) clearer than checking for throwing a nomethod error?

File: shoes-core/spec/shoes/shared_examples/clickable.rb [hunk 3]
```diff
@@ -2,4 +2,18 @@
   it { is_expected.to respond_to :click }
   it { is_expected.to respond_to :release }
   it { is_expected.to respond_to :register_click }
+
+  it "can chain click" do
+    result = subject.click do
+    end
```
Comment (PragTob) [inline shoes-core/spec/shoes/shared_examples/clickable.rb]: minor thing but maybe `subject.click {}` reads nicer? or even `subject.click do end` - the line break sort of throws me off

File: shoes-core/spec/shoes/shared_examples/clickable.rb [hunk 4]
```diff
@@ -2,4 +2,18 @@
...
+
+    expect(result).to eq(subject)
+  end
+
+  it "can chain release" do
+    result = subject.release do
+    end
```
Comment (PragTob) [inline shoes-core/spec/shoes/shared_examples/clickable.rb]: Same line break thing here :)

File: shoes-core/lib/shoes/common/clickable.rb (hunk 1 above)
Comment (jasonrclark) [inline shoes-core/lib/shoes/common/clickable.rb]: Yeah, I wondered the same. Entered #1340 to not forget.

File: shoes-core/spec/shoes/shared_examples/clickable.rb (hunk 3 above)
Comment (jasonrclark) [inline shoes-core/spec/shoes/shared_examples/clickable.rb]: I always find the `{}` makes me think it's a hash... will see if Rubocop is happy with `do end` since I also wasn't a huge fan of the separate lines.
