### PR TITLE
Executable changes in shoes

### LINKED ISSUE #1300: Better error messages if running on unsupported Ruby?
Per #1239, the errors you get if trying to run on MRI are definitely cryptic. Can we do any better at installation or runtime to detect what's up and point them in the right direction?

### LINKED ISSUE #1342: can't run shoes jar
I have been trying to make a shoes app but when I package it with `shoes -p swt:jar SnowShoes.rb` and try to run the file with `java -jar pkg/redxtech_snowshoes.jar`, I get an error.
Here it is:
```
Ignoring shoes-core-4.0.0.pre7 because its extensions are not built.  Try: gem pristine shoes-core --version 4.0.0.pre7
LoadError: no such file to load -- shoes
  require at org/jruby/RubyKernel.java:1040
  require at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
   (root) at file:/C:/Users/redxtech/RubymineProjects/SnowShoesProd/pkg/redxtech_snowshoes.jar!/META-INF/init.rb:8
  require at org/jruby/RubyKernel.java:1040
   (root) at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:1
  require at /C:/Users/redxtech/AppData/Local/Temp/jruby404529263560838882extract/jruby-stdlib-1.7.26.jar!/META-INF/jruby.home/lib/ruby/shared/rubygems/core_ext/kernel_require.rb:54
ERROR: org.jruby.embed.EvalFailedException: (LoadError) no such file to load -- shoes
```

I have tried `jruby -S gem pristine shoes-core` and it has confirmed that shoes-core 4.0.0.pre7 has been made pristine, but the same error keeps happeneing.

If any more information is needed, let me know.

Any ideas on why this is happening?

### PR DESCRIPTION
**Pull request by jasonrclark**
Fixes #1342. Fixes #1300.

This should finally get packaging back in a kinder state, at least from what I can tell. It shifts the "native" executable we do to pull shell hijinks during installation up into the `shoes` gem which isn't included for packaging.

While I'm fiddling with the executables, I also want to get the JRuby warning messages in (#1300), since that'll take changes to the scripts. Testing it all at once will be a significant time savings for me, and it won't bulk this PR up too much.

## Points for discussion
This does start introducing a bit of stuff in `shoes` itself. It's cross-cutting stuff, so I don't feel too bad, but it's no longer quite a meta-gem. Should we restructure with its own subdirectory like the other gems?

## TODO

* [x] REMOVE VERSION BUMP. It makes testing easier, but should be dropped before this merges.
* [x] Move "native" executable up to `shoes` so `shoes-core` avoids our warbler issues.
* [x] Add warning message if we detect we're not running on JRuby (ala https://github.com/shoes/shoes4/issues/1300#issuecomment-266650264)
* [x] Test clean source pull and run on:
  * [x] Mac
  * [x] Linux
  * [x] Windows
* [x] Test gem installation on:
  * [x] Mac
  * [x] Linux
  * [x] Windows
* [x] Test packaging on:
  * [x] Mac
  * [x] Linux
  * [x] ~~Windows~~ :sob: (#1351)

### CODE REVIEW

**Comment by PragTob** [comment]
Looks good. One of the builds was failing but it seemed rather random so I restarted it.

About the restructuring/meta gem - I somehow feel it's ok for a meta gem to have some glue code. It feels nice to me that there's the small lightweight gem up top with the Gemfile/gemspec etc. so it feels more or less like a normal gem repository.

If the logic grows, I'd actually be in favor of moving it in its own directory... but as another gem. Like, dunno `shoes-launcher` or whatever it does then. And the way you tell it, especially with the likes of #1300 and #1344 that might happen. 

I know, I know... I like them small little gems :smiley: 

Thanks for the work! :+1:

**Comment by jasonrclark** [comment]
Oh, and to the separate gem thought, I don't think this'll push us there, but I have some ideas around #718 which would lead to something like `shoes-launcher`. While it's marked for 4.1, I've been playing with the idea in my head so I might end up pursuing it eventually. We'll see!

File: shoes-swt/lib/shoes/swt/generate_backend.rb [hunk 1]
```diff
@@ -1,7 +1,35 @@
 require 'rbconfig'
```
Comment (PragTob) [inline shoes-swt/lib/shoes/swt/generate_backend.rb]: frozen string literal magic :D #annoyingthingstobisays

File: shoes-swt/lib/shoes/swt/generate_backend.rb [hunk 2]
```diff
@@ -1,7 +1,35 @@
...
+The shoes-swt backend requires a 9.X version of JRuby.
+
+You are running the following Ruby instead:
+
+  #{RUBY_DESCRIPTION}
+
+Please download JRuby from http://jruby.org (or your favorite Ruby version
+manager), reinstall the `shoes` gem on that Ruby, and try again.
+
+Sorry for the inconvenience!
```
Comment (PragTob) [inline shoes-swt/lib/shoes/swt/generate_backend.rb]: I like putting it right here, that's nice!

I think we might also link to our README. My experience with long error messages/warnings is that they get out of sync quickly and somewhat unwieldly while the README is more up to date and covers more ground... or should :)

To avoid misconceptions, I think this is concise enough to stay just thinking that a link to the README for further information might be helpful.

File: shoes-swt/spec/shoes/swt/generate_backend_spec.rb [hunk 3]
```diff
@@ -0,0 +1,32 @@
...
+
+    Shoes::SelectedBackend.validate
+  end
+
+  def reset_ruby_engine(engine)
+    Object.instance_eval do
+      remove_const(:RUBY_ENGINE)
+      const_set(:RUBY_ENGINE, engine)
+    end
+  end
```
Comment (PragTob) [inline shoes-swt/spec/shoes/swt/generate_backend_spec.rb]: magic

File: shoes-swt/lib/shoes/swt/generate_backend.rb (hunk 1 above)
Comment (jasonrclark) [inline shoes-swt/lib/shoes/swt/generate_backend.rb]: Will add this one, but I'm thinking it'll be worth doing #1284 soon and then enabling Rubocop to enforce going forward.

File: shoes-swt/lib/shoes/swt/generate_backend.rb (hunk 2 above)
Comment (jasonrclark) [inline shoes-swt/lib/shoes/swt/generate_backend.rb]: Linking to our material's a great idea. Pushed up a revision... what do you think?

**Comment by PragTob** [comment]
:+1:

**Comment by jasonrclark** [comment]
Wow, my instincts were right to do the exhaustive testing with this. Found separate bugs on both Windows and Linux with the "easy" script changes :rofl: 

Good news, packaging is working pretty smoothly in my simple cases (not going too deep yet) on both Linux and Mac, both from source and installed gems. Windows, ah Windows... ran straight into #1351 which will need some out of band love.

So, I think this one's ready to launch once you give the 👌  @PragTob.

**Comment by PragTob** [comment]
:heart: :star2: 

Thanks for your relentless hard and good work! :)
