### PR TITLE
Correctly using parents margin for background

### LINKED ISSUE #1193: Margins for slot and background broken (samples/good-vjot)
selection_024
(Shoes 4 to the left, 3.2 to the right, if you go back to #255 you see that it used to work)

Might investigate further later on, seems like an annoying breakage :(

### PR DESCRIPTION
**Pull request by PragTob**
This rethinks ParentDimension a bunch, from 3 main observations:

* we should not position backgrounds, it works when they are
  the first element in a slot but not after that
* backgrounds need to respect the margins of parents, which means
  their absolute_starts should be the parents element_starts
* beyond that, there doesn't seem to be much need to get
  parent position values, as they all somehow end up
  influencing absolute_top/left (I hope, this might come back
  later)

That also removes a lot of ambiguity and difficult code.
Better code through increased domain understanding :+1:

* fixes #1193 

succeeds #1203 

A look at a couple of examples between shoes 4 and shoes 3.2:

```ruby
Shoes.app do
  stack margin: 20, height: 100 do
    background green
  end

  stack margin: 40, height: 100 do
    background blue
  end
end
```

selection_031

```ruby
Shoes.app do
  banner 'What up'
  background red
end
```

(see #599)

selection_032

```ruby
Shoes.app do
  stack height: 150, bottom: 50 do
    background red
  end
end
```

(some more advanced positioning)

selection_033

```ruby
Shoes.app do
  stack margin: 20, height: 200 do
    background blue
    background green, margin: 20
  end
end
```

(double margin)

selection_034

last but not least `good-vjot.rb` which still has some issues but those are of another nature (or at least I believe so ;))

good-vjot

### CODE REVIEW

File: shoes-core/lib/shoes/dimension.rb [hunk 1]
```diff
@@ -253,27 +249,18 @@ def extent
...
-      if parent.element_end
-        # Why subtracting an absolute from an element dimension value? A
-        # diagram helped me reason out what we wanted.
-        #
-        # parent.      parent.      self.       self.    parent.      parent.
-        # abs_start    elem_start   abs_start   abs_end  elem_end     abs_end
-        # |   margin   |            |           |        |   margin   |
-        #
-        # To get our extent respecting the parent's margins, it's our absolute
-        # start, minus parent's element end (so we don't blow past the margin)
```
Comment (jasonrclark) [inline shoes-core/lib/shoes/dimension.rb]: As the author of this comment, I'm so glad to see it going away :)

**Comment by jasonrclark** [comment]
Code here looks good. I'm going to do some testing on it this afternoon and evening, and assuming everything is happy will merge and :boat: to pre5!
